### ISSUE TITLE
Event matching query does not exist

### ISSUE THREAD

**Issue by zecke** [dlespiau/patchwork#166]
Sorry to bother, is there anything I should have initialized and forgot? Is this a fatal error?

Traceback (most recent call last):
  File "./../../patchwork/bin/parsemail.py", line 890, in <module>
    sys.exit(main(sys.argv))
  File "./../../patchwork/bin/parsemail.py", line 878, in main
    return parse_mail(mail)
  File "./../../patchwork/bin/parsemail.py", line 796, in parse_mail
    revision.add_patch(patch, content.patch_order)
  File "/usr/home/patchwork/patchwork/patchwork/models.py", line 620, in add_patch
    series_revision_complete.send(sender=self.**class**, revision=self)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, *_named)
  File "/usr/home/patchwork/patchwork/patchwork/models.py", line 859, in _on_revision_complete
    new_revision = Event.objects.get(name='series-new-revision')
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(_args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
patchwork.models.DoesNotExist: Event matching query does not exist.

**Comment by dlespiau** [comment]
Hi,

The installation instructions are very out of date :/

You need to load a bit of data in the DB to get going:

```
    $ ./manage.py loaddata default_states
    $ ./manage.py loaddata default_tags
    $ ./manage.py loaddata default_events
```

There's also a whole section missing about redis/celery. That's how I do background tasks to send emails to reviewers.

Let's keep that bug open as a reminder I need to rewrite the full installation document.
