### ISSUE TITLE
git-pw apply/apply-patch failing

### ISSUE THREAD

**Issue by ghost** [dlespiau/patchwork#181]
Using the freedesktop instance : 

```
$ git pw apply-patch 81924
Traceback (most recent call last):
  File "/home/djdeath/bin/git-pw", line 1028, in <module>
    ret = git_pw.run()
  File "/home/djdeath/bin/git-pw", line 831, in run
    ret = getattr(self, method)()
  File "/home/djdeath/bin/git-pw", line 640, in do_apply_patch
    return self.am(patch.absolute_url('/mbox/'))
  File "/home/djdeath/bin/git-pw", line 599, in am
    r = requests.get(mailbox_url, params)
TypeError: get() takes exactly 1 argument (2 given)
```

```
$ python --version
Python 2.7.6
```

**Comment by dlespiau** [comment]
hhuum, I wonder which version of requests you have, probably too old... Debian!

**Comment by dlespiau** [comment]
Oh and that is fixed by Lionel's pull request: https://github.com/dlespiau/patchwork/pull/186
