### ISSUE TITLE
Unable to post-result is email notifications are enabled for a test

### ISSUE THREAD

**Issue by avagin** [dlespiau/patchwork#183]
```
[root@zdtm criu]# git pw post-result 30 travis-ci failure
fatal: Internal error, you found a bug in Patchwork!
```

How can I get more information about this error?

**Comment by avagin** [comment]
```
Internal Server Error: /api/1.0/series/30/revisions/1/test-results/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 402, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 399, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/patchwork/lib/apache2/../../patchwork/views/api.py", line 469, in create
    Q(revision=rev), {'revision': rev})
  File "/srv/patchwork/lib/apache2/../../patchwork/views/api.py", line 456, in handle_test_results
    email.send()
  File "/usr/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection.starttls(keyfile=self.ssl_keyfile, certfile=self.ssl_certfile)
  File "/usr/lib64/python2.7/smtplib.py", line 644, in starttls
    raise SMTPException("STARTTLS extension not supported by server.")
SMTPException: STARTTLS extension not supported by server.

Request repr():
<WSGIRequest
path:/api/1.0/series/30/revisions/1/test-results/,
GET:<QueryDict: {}>,
POST:<could not parse>,
COOKIES:{},
META:{'CONTENT_LENGTH': '46',
 'CONTENT_TYPE': 'application/json',
 'CONTEXT_DOCUMENT_ROOT': '/var/www/html',
 'CONTEXT_PREFIX': '',
 u'CSRF_COOKIE': u'gWZXSTzsefSXeHJZFBKMPs6Qh4xf4XmY',
 'DOCUMENT_ROOT': '/var/www/html',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Basic Y3JpdS1yb2JvdDprMHR1d1FlMmU2M3hnQTZUT01zTQ==',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'zdtm.openvz.org',
 'HTTP_USER_AGENT': 'python-requests/2.9.1',
 'PATH_INFO': u'/api/1.0/series/30/revisions/1/test-results/',
 'PATH_TRANSLATED': '/srv/patchwork/lib/apache2/patchwork.wsgi/api/1.0/series/30/revisions/1/test-results/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '199.115.105.187',
 'REMOTE_PORT': '39360',
 'REQUEST_METHOD': 'POST',
 'REQUEST_SCHEME': 'https',
 'REQUEST_URI': '/api/1.0/series/30/revisions/1/test-results/',
 'SCRIPT_FILENAME': '/srv/patchwork/lib/apache2/patchwork.wsgi',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '199.115.105.187',
 'SERVER_ADMIN': 'root@localhost',
 'SERVER_NAME': 'zdtm.openvz.org',
 'SERVER_PORT': '443',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SIGNATURE': '',
 'SERVER_SOFTWARE': 'Apache/2.4.18 (Fedora) OpenSSL/1.0.2g-fips mod_wsgi/4.4.8 Python/2.7.11 Phusion_Passenger/4.0.59',
 'SSL_TLS_SNI': 'zdtm.openvz.org',
 'UNIQUE_ID': 'Vx6JjwKvFCOLxH3V6TUi6wAAAAQ',
 'apache.version': (2, 4, 18),
 'mod_wsgi.application_group': 'zdtm.openvz.org|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.enable_sendfile': '0',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '443',
 'mod_wsgi.process_group': '',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.request_start': '1461619087396727',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.script_start': '1461619087397194',
 'mod_wsgi.version': (4, 4, 8),
 'wsgi.errors': <mod_wsgi.Log object at 0x7f9bb06e4540>,
 'wsgi.file_wrapper': <type 'mod_wsgi.FileWrapper'>,
 'wsgi.input': <mod_wsgi.Input object at 0x7f9baeb98f30>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}>
```

**Comment by avagin** [comment]
The problem was fixed, when I enabled ssl for postfix. Sorry for the noise.
